# ---- Stage 1: Install dependencies and build ----
FROM node:24 AS builder

WORKDIR /app

# Copy source files
COPY . .

# Install dependencies and build.
# Cache node_modules for future builds.
RUN \
  --mount=type=cache,target=/app/node_modules \
  npm install && \
  npm ci && \
  npm run build

# ---- Stage 2: Serve with a static web server ----
FROM nginx:stable-alpine

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# Copy built assets from builder
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Run start script
CMD ["nginx", "-g", "daemon off;"]
