name: whiteboard_editor

services:
  reverse_proxy:
    # Maps urls to ports to various services.
    # Main entry point for external clients.
    build: ReverseProxy
    ports:
      - ${TABLE_EDITOR_HTTP_PORT-8080}:8080
      - ${TABLE_EDITOR_HTTPS_PORT-4430}:4430
    environment:
      TABLE_EDITOR_FRONTEND_PORT: ${TABLE_EDITOR_FRONTEND_PORT-3000}
      TABLE_EDITOR_WS_PORT: ${TABLE_EDITOR_WS_PORT-4000}
    depends_on:
      - frontend
  
  frontend:
    # Frontend code to serve to client.
    # Built using Vite, served with nginx
    build: Frontend
