name: whiteboard_editor

services:
  reverse_proxy:
    # Maps urls to ports to various services.
    # Main entry point for external clients.
    build: ReverseProxy
    ports:
      - ${WHITEBOARD_EDITOR_HTTP_PORT-8080}:8080
      - ${WHITEBOARD_EDITOR_HTTPS_PORT-4430}:4430
    environment:
      WHITEBOARD_EDITOR_FRONTEND_PORT: ${WHITEBOARD_EDITOR_FRONTEND_PORT-3000}
      WHITEBOARD_EDITOR_WS_PORT: ${WHITEBOARD_EDITOR_WS_PORT-4000}
    volumes:
      - type: bind
        source: ReverseProxy/key.pem
        target: /app/key.pem
      - type: bind
        source: ReverseProxy/cert.pem
        target: /app/cert.pem
    depends_on:
      - frontend
      - web_socket_server
  
  frontend:
    # Frontend code to serve to client.
    # Built using Vite, served with nginx
    build: Frontend
    depends_on:
      - web_socket_server

  web_socket_server:
    # Handles web sockets for providing real-time interaction with clients.
    # Built in Rust.
    build: WebSocketServer
    environment:
      # Make sure to set MONGO_URI in .env
      MONGO_URI: ${WHITEBOARD_EDITOR_MONGO_URI}
