// === CreateCanvas.ts =========================================================
//
// Defines protocol for creating a new Canvas, enabling passing data from the
// CreateCanvas tool to the CreateCanvas menu.
//
// =============================================================================

// === interface NewCanvasDimensions ===========================================
//
// Defines basic dimentions of a new canvas. Generated by the CreateCanvas tool
// and passed to the CreateCanvas menu.
//
// =============================================================================
export interface NewCanvasDimensions {
  originX: number;
  originY: number;
  width: number;
  height: number;
}// -- end interface NewCanvasDimensions
