# Runs tests on built images.
on:
  push:
    branches:
      - feat/lint_check
  workflow_call:
    secrets:
      TEST_CR_URI:
        description: "URL at which the container registry is located"
        required: true
      TEST_CR_PASS:
        description: "Password with which to log into container registry"
        required: true
      TEST_CR_USERNAME:
        description: "Username with which to log into container registry"
        required: true
jobs:
  push_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Build Images
        run: |
          docker compose build
      - name: Publish Images
        env:
          CR_URI: ${{ secrets.TEST_CR_URI }}
          CR_PASS: ${{ secrets.TEST_CR_PASS }}
          CR_USERNAME: ${{ secrets.TEST_CR_USERNAME }}
        run: |
          # log into CR
          printenv CR_PASS | docker login -u "${CR_USERNAME}" --password-stdin

          # publish to CR
          docker compose publish "${CR_URI}:latest"
