# Runs tests on built images.
on:
  push:
    branches:
      - feat/lint_check
jobs:
  docker_images:
    # ensure that all images can build, at a bare minimum
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: build frontend
        run: |
          docker compose build frontend

          echo 'service "frontend" build successfully'
      - name: build web_socket_server
        run: |
          docker compose build web_socket_server

          echo 'service "web_socket_server" build successfully'
      - name: build reverse_proxy
        run: |
          docker compose build reverse_proxy

          echo 'service "reverse_proxy" build successfully'
