# Runs tests on built images.
on:
  push:
    branches:
      - feat/lint_check
jobs:
  test_frontend:
    # test frontend image in isolation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: install
        run: |
          # install dependencies via yarn
          cd Frontend

          yarn install

          echo 'service "frontend" installed dependencies successfully'
      - name: lint
        run: |
          cd Frontend

          yarn run lint

          echo 'service "frontend" linted successfully'
      - name: build
        run: |
          docker compose build frontend

          echo 'service "frontend" built successfully'

  test_web_socket_server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: build
        # name sure the image builds, at a minimum
        run: |
          docker compose build web_socket_server

          echo 'service "web_socket_server" built successfully'

  test_reverse_proxy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: build
        # name sure the image builds, at a minimum
        run: |
          docker compose build reverse_proxy

          echo 'service "reverse_proxy" built successfully'
