# Test frontend service
on:
  push:
    paths:
      - 'Frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_frontend.yml'
  pull_request:
    on:
      - opened
jobs:
  test_lint_frontend:
    # run linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v5

      - name: Install dependencies
        id: install-dependencies
        run: |
          # install dependencies via yarn
          cd Frontend

          yarn install

          echo 'service "frontend" installed dependencies successfully'

      - name: Run lint
        id: lint
        run: |
          cd Frontend

          yarn run lint

          echo 'service "frontend" linted successfully'

  test_build_frontend:
    # make sure image builds
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v5

      - name: Set up Docker
        id: docker-setup
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Build frontend
        id: build-frontend-cached
        uses: docker/build-push-action@v6
        with:
          context: Frontend
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/frontend:test

          # cache settings
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/frontend:buildcache,mode=max

