# Test web_socket_server service
name: Test Web Socket Server

on:
  push:
    paths:
      - 'WebSocketServer/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_web_socket_server.yml'
  pull_request:
    on:
      - opened
jobs:
  run_cargo_tests_web_socket_server:
    # Build web_socket_server_tester and run cargo tests within
    # web_socket_server_tester
    name: Run Cargo Unit Tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log into Github Container Registry
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Container Registry cache
        id: build-cached
        uses: docker/build-push-action@v6
        with:
          context: WebSocketServer
          target: test_runtime
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/web_socket_server_tester:test

          # cache settings
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/web_socket_server_tester:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/web_socket_server_tester:buildcache,mode=max

      - name: Start test database
        shell: bash
        run: |
          docker compose -p ${{ github.job }} up --build -d test_db

      - name: Run Cargo tests
        id: run-cargo-tests
        env:
          # Needed for docker compose to properly identify the built image (see
          # image tag for web_socket_server_tester in docker-compose.yml)
          WHITEBOARD_EDITOR_CR_URI: ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}
          WHITEBOARD_EDITOR_TAG: test
        run: |
          docker compose up web_socket_server_tester

      - name: Tear down test database
        id: tear-down-test-db
        if: always()
        shell: bash
        run: |
          # Just run for all services, in case we started more services than
          # just test_db.
          docker compose down -v
