# Test rest_api service
on:
  push:
    paths:
      - 'RestAPI/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_rest_api.yml'
  pull_request:
    on:
      - opened
jobs:
  test_build_rest_api:
    # make sure image builds
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: build
        run: |
          docker compose build rest_api

          echo 'service "rest_api" built successfully'
  run_supertest:
    # Run supertest tests within the rest_api container
    runs-on: ubuntu-24.04
    steps:
        # check out repo
      - uses: actions/checkout@v5
        # set up test database
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Start test database
        shell: bash
        run: |
          docker compose -p ${{ github.job }} up --build -d test_db
      - name: Set up test env
        env:
          TEST_ENV: |
            # Secret for signing JSON Web Tokens (JWTs)
            # Should be at least 64 characters in length
            WHITEBOARD_EDITOR_JWT_SECRET=2KUU6DNUY6XGBL2NQFXDXGGVOJ63A75RYSZ5SKD3PMYPCXC6L3I3WRDZER5JA4GC2SOQ2K6W66JUQ3XMM3QT6PXC4UKAFXDDDIIRP4A=

            # URI to access Mongo database
            # Format: mongodb+srv://<USER>:<PASSWORD>@<URL>/<DATABASE>
            WHITEBOARD_EDITOR_MONGO_URI=mongodb://test_db:27017/testdb

            # Number of seconds before a jwt expires
            WHITEBOARD_EDITOR_JWT_EXPIRATION_SECS=999999999

            # To set exposed port for testing
            WHITEBOARD_EDITOR_REST_API_PORT=3001
        run: |
          printenv TEST_ENV > .env
      - name: docker compose up
        run: docker compose -p ${{ github.job }} up --build -d rest_api
      - name: Print rest api initial logs
        run: |
          sleep 3

          docker compose -p ${{ github.job }} logs rest_api
      - name: Run supertest
        run: docker compose -p ${{ github.job }} exec rest_api yarn run test
      - name: Tear down test database
        if: always()
        shell: bash
        run: |
          docker compose -p ${{ github.job }} down -v test_db
      - name: Tear down docker compose
        if: always()
        run: docker compose -p ${{ github.job }} down
