# Test web_socket_server service

on:
  push:
    paths:
      - 'WebSocketServer/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_web_socket_server.yml'
  pull_request:
    on:
      - opened
jobs:
  run_cargo_tests_web_socket_server:
    # Build web_socket_server_builder and run cargo tests within
    # web_socket_server_builder
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log into Github Container Registry
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Container Registry cache
        id: build-cached
        uses: docker/build-push-action@v6
        with:
          context: WebSocketServer
          push: false
          tags: ghcr.io/${{ github.repository_id }}/web_socket_server:test

          # cache settings
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_id }}/web_socket_server:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_id }}/web_socket_server:buildcache,mode=max

      - name: Run Cargo tests
        id: run-cargo-tests
        run: |
          docker run --entrypoint 'cargo test' ghcr.io/${{ github.repository_id }}/web_socket_server:test
