# Test rest_api service
name: Test Rest API

on:
  push:
    paths:
      - 'RestAPI/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_rest_api.yml'
  pull_request:
    on:
      - opened

jobs:
  run_supertest_rest_api:
    # make sure image builds
    name: Run Supertest on Rest API
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Log into Github Container Registry
        id: login-ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Container Registry cache
        id: build-cached
        uses: docker/build-push-action@v6
        with:
          context: RestAPI
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/rest_api:test

          # cache settings
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/rest_api:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}/rest_api:buildcache,mode=max

      - name: Set up test env
        id: test-env-setup
        env:
          TEST_ENV: |
            # Secret for signing JSON Web Tokens (JWTs)
            # Should be at least 64 characters in length
            WHITEBOARD_EDITOR_JWT_SECRET=2KUU6DNUY6XGBL2NQFXDXGGVOJ63A75RYSZ5SKD3PMYPCXC6L3I3WRDZER5JA4GC2SOQ2K6W66JUQ3XMM3QT6PXC4UKAFXDDDIIRP4A=

            # URI to access Mongo database
            # Format: mongodb+srv://<USER>:<PASSWORD>@<URL>/<DATABASE>
            WHITEBOARD_EDITOR_MONGO_URI=mongodb://test_db:27017/testdb

            # Number of seconds before a jwt expires
            WHITEBOARD_EDITOR_JWT_EXPIRATION_SECS=999999999

            # To set exposed port for testing
            WHITEBOARD_EDITOR_REST_API_PORT=3001
        run: |
          printenv TEST_ENV > .env

      - name: Start test database
        shell: bash
        run: |
          docker compose -p ${{ github.job }} up --build -d test_db

      - name: Run supertest
        id: run-supertest
        env:
          # docker compose will identify the built image using these variables
          WHITEBOARD_EDITOR_CR_URI: ghcr.io/${{ github.repository_owner }}/${{ github.repository_id }}
          WHITEBOARD_EDITOR_TAG: test
        run: |
          docker compose -p ${{ github.job }} run --entrypoint "yarn test" rest_api

      - name: Tear down test database
        id: tear-down-test-db
        if: always()
        shell: bash
        run: |
          # Just run for all services, in case we started more services than
          # just test_db.
          docker compose -p ${{ github.job }} down -v
