# Test reverse_proxy service
name: Test Reverse Proxy

on:
  push:
    paths:
      - 'ReverseProxy/**'
      - 'docker-compose.yml'
      - '.github/workflows/test_reverse_proxy.yml'
  pull_request:
    on:
      - opened
  workflow_call:
    secrets:
      CONTAINER_REGISTRY_URI:
        description: "The URI from which to pull base images."
        required: false

jobs:
  test_build_reverse_proxy:
    # ensure the image builds successfully
    name: Test Build Reverse Proxy
    runs-on: ubuntu-22.04
    env:
      WHITEBOARD_EDITOR_CONTAINER_REGISTRY_URI: ${{ secrets.CONTAINER_REGISTRY_URI }}
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: build
        # name sure the image builds, at a minimum
        run: |
          docker compose build reverse_proxy

          echo 'service "reverse_proxy" built successfully'
